{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "logstream-workergroup.serviceAccountName" . }}
  labels:
    {{- include "logstream-workergroup.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.rbac.annotations  | nindent 4 }}

{{- end }}
