{{- if .Values.rbac.create }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "outpost.rbacName" . }}
  labels:
    {{- include "outpost.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
{{- toYaml .Values.rbac.roleRules | nindent 2}}
{{- range .Values.rbac.extraRoleRules }}
  - {{ toYaml . | indent 4 | trim }}
{{- end }}
{{- end }}

