{{- if .Values.rbac.create }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "common.fullname" . }}:{{ include "common.name" . }}:{{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  {{- toYaml .Values.rbac.roleRules | nindent 2}}
  {{- range .Values.rbac.extraRoleRules }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
